### ISSUE TITLE
try to run train.py meet error

### ISSUE THREAD

**Issue by csufangyu** [DrSleep/light-weight-refinenet#15]
thanks for your work！I want to run your code, but I meet a error,could you help me？thanks very much！

`/home/robot/fangyu_pytorch/bin/python /home/robot/PycharmProjects/light-weight-refinenet_train/src/train.py --enc 50
INFO:__main__: Loaded Segmenter 50, ImageNet-Pre-Trained=True, #PARAMS=27.40M
/home/robot/fangyu_pytorch/lib/python3.6/site-packages/torch/nn/modules/loss.py:206: UserWarning: NLLLoss2d has been deprecated. Please use NLLLoss instead as a drop-in replacement and see http://pytorch.org/docs/master/nn.html#torch.nn.NLLLoss for more details.
  warnings.warn("NLLLoss2d has been deprecated. "
INFO:__main__: Training Process Starts
INFO:__main__: Created train set = 795 examples, val set = 654 examples
INFO:__main__: Training Stage 0
INFO:__main__: Enc. parameter: module.conv1.weight
INFO:__main__: Enc. parameter: module.bn1.weight
INFO:__main__: Enc. parameter: module.bn1.bias
INFO:__main__: Enc. parameter: module.layer1.0.conv1.weight
INFO:__main__: Enc. parameter: module.layer1.0.bn1.weight
INFO:__main__: Enc. parameter: module.layer1.0.bn1.bias
INFO:__main__: Enc. parameter: module.layer1.0.conv2.weight
INFO:__main__: Enc. parameter: module.layer1.0.bn2.weight
INFO:__main__: Enc. parameter: module.layer1.0.bn2.bias
INFO:__main__: Enc. parameter: module.layer1.0.conv3.weight
INFO:__main__: Enc. parameter: module.layer1.0.bn3.weight
INFO:__main__: Enc. parameter: module.layer1.0.bn3.bias
INFO:__main__: Enc. parameter: module.layer1.0.downsample.0.weight
INFO:__main__: Enc. parameter: module.layer1.0.downsample.1.weight
INFO:__main__: Enc. parameter: module.layer1.0.downsample.1.bias
INFO:__main__: Enc. parameter: module.layer1.1.conv1.weight
INFO:__main__: Enc. parameter: module.layer1.1.bn1.weight
INFO:__main__: Enc. parameter: module.layer1.1.bn1.bias
INFO:__main__: Enc. parameter: module.layer1.1.conv2.weight
INFO:__main__: Enc. parameter: module.layer1.1.bn2.weight
INFO:__main__: Enc. parameter: module.layer1.1.bn2.bias
INFO:__main__: Enc. parameter: module.layer1.1.conv3.weight
INFO:__main__: Enc. parameter: module.layer1.1.bn3.weight
INFO:__main__: Enc. parameter: module.layer1.1.bn3.bias
INFO:__main__: Enc. parameter: module.layer1.2.conv1.weight
INFO:__main__: Enc. parameter: module.layer1.2.bn1.weight
INFO:__main__: Enc. parameter: module.layer1.2.bn1.bias
INFO:__main__: Enc. parameter: module.layer1.2.conv2.weight
INFO:__main__: Enc. parameter: module.layer1.2.bn2.weight
INFO:__main__: Enc. parameter: module.layer1.2.bn2.bias
INFO:__main__: Enc. parameter: module.layer1.2.conv3.weight
INFO:__main__: Enc. parameter: module.layer1.2.bn3.weight
INFO:__main__: Enc. parameter: module.layer1.2.bn3.bias
INFO:__main__: Enc. parameter: module.layer2.0.conv1.weight
INFO:__main__: Enc. parameter: module.layer2.0.bn1.weight
INFO:__main__: Enc. parameter: module.layer2.0.bn1.bias
INFO:__main__: Enc. parameter: module.layer2.0.conv2.weight
INFO:__main__: Enc. parameter: module.layer2.0.bn2.weight
INFO:__main__: Enc. parameter: module.layer2.0.bn2.bias
INFO:__main__: Enc. parameter: module.layer2.0.conv3.weight
INFO:__main__: Enc. parameter: module.layer2.0.bn3.weight
INFO:__main__: Enc. parameter: module.layer2.0.bn3.bias
INFO:__main__: Enc. parameter: module.layer2.0.downsample.0.weight
INFO:__main__: Enc. parameter: module.layer2.0.downsample.1.weight
INFO:__main__: Enc. parameter: module.layer2.0.downsample.1.bias
INFO:__main__: Enc. parameter: module.layer2.1.conv1.weight
INFO:__main__: Enc. parameter: module.layer2.1.bn1.weight
INFO:__main__: Enc. parameter: module.layer2.1.bn1.bias
INFO:__main__: Enc. parameter: module.layer2.1.conv2.weight
INFO:__main__: Enc. parameter: module.layer2.1.bn2.weight
INFO:__main__: Enc. parameter: module.layer2.1.bn2.bias
INFO:__main__: Enc. parameter: module.layer2.1.conv3.weight
INFO:__main__: Enc. parameter: module.layer2.1.bn3.weight
INFO:__main__: Enc. parameter: module.layer2.1.bn3.bias
INFO:__main__: Enc. parameter: module.layer2.2.conv1.weight
INFO:__main__: Enc. parameter: module.layer2.2.bn1.weight
INFO:__main__: Enc. parameter: module.layer2.2.bn1.bias
INFO:__main__: Enc. parameter: module.layer2.2.conv2.weight
INFO:__main__: Enc. parameter: module.layer2.2.bn2.weight
INFO:__main__: Enc. parameter: module.layer2.2.bn2.bias
INFO:__main__: Enc. parameter: module.layer2.2.conv3.weight
INFO:__main__: Enc. parameter: module.layer2.2.bn3.weight
INFO:__main__: Enc. parameter: module.layer2.2.bn3.bias
INFO:__main__: Enc. parameter: module.layer2.3.conv1.weight
INFO:__main__: Enc. parameter: module.layer2.3.bn1.weight
INFO:__main__: Enc. parameter: module.layer2.3.bn1.bias
INFO:__main__: Enc. parameter: module.layer2.3.conv2.weight
INFO:__main__: Enc. parameter: module.layer2.3.bn2.weight
INFO:__main__: Enc. parameter: module.layer2.3.bn2.bias
INFO:__main__: Enc. parameter: module.layer2.3.conv3.weight
INFO:__main__: Enc. parameter: module.layer2.3.bn3.weight
INFO:__main__: Enc. parameter: module.layer2.3.bn3.bias
INFO:__main__: Enc. parameter: module.layer3.0.conv1.weight
INFO:__main__: Enc. parameter: module.layer3.0.bn1.weight
INFO:__main__: Enc. parameter: module.layer3.0.bn1.bias
INFO:__main__: Enc. parameter: module.layer3.0.conv2.weight
INFO:__main__: Enc. parameter: module.layer3.0.bn2.weight
INFO:__main__: Enc. parameter: module.layer3.0.bn2.bias
INFO:__main__: Enc. parameter: module.layer3.0.conv3.weight
INFO:__main__: Enc. parameter: module.layer3.0.bn3.weight
INFO:__main__: Enc. parameter: module.layer3.0.bn3.bias
INFO:__main__: Enc. parameter: module.layer3.0.downsample.0.weight
INFO:__main__: Enc. parameter: module.layer3.0.downsample.1.weight
INFO:__main__: Enc. parameter: module.layer3.0.downsample.1.bias
INFO:__main__: Enc. parameter: module.layer3.1.conv1.weight
INFO:__main__: Enc. parameter: module.layer3.1.bn1.weight
INFO:__main__: Enc. parameter: module.layer3.1.bn1.bias
INFO:__main__: Enc. parameter: module.layer3.1.conv2.weight
INFO:__main__: Enc. parameter: module.layer3.1.bn2.weight
INFO:__main__: Enc. parameter: module.layer3.1.bn2.bias
INFO:__main__: Enc. parameter: module.layer3.1.conv3.weight
INFO:__main__: Enc. parameter: module.layer3.1.bn3.weight
INFO:__main__: Enc. parameter: module.layer3.1.bn3.bias
INFO:__main__: Enc. parameter: module.layer3.2.conv1.weight
INFO:__main__: Enc. parameter: module.layer3.2.bn1.weight
INFO:__main__: Enc. parameter: module.layer3.2.bn1.bias
INFO:__main__: Enc. parameter: module.layer3.2.conv2.weight
INFO:__main__: Enc. parameter: module.layer3.2.bn2.weight
INFO:__main__: Enc. parameter: module.layer3.2.bn2.bias
INFO:__main__: Enc. parameter: module.layer3.2.conv3.weight
INFO:__main__: Enc. parameter: module.layer3.2.bn3.weight
INFO:__main__: Enc. parameter: module.layer3.2.bn3.bias
INFO:__main__: Enc. parameter: module.layer3.3.conv1.weight
INFO:__main__: Enc. parameter: module.layer3.3.bn1.weight
INFO:__main__: Enc. parameter: module.layer3.3.bn1.bias
INFO:__main__: Enc. parameter: module.layer3.3.conv2.weight
INFO:__main__: Enc. parameter: module.layer3.3.bn2.weight
INFO:__main__: Enc. parameter: module.layer3.3.bn2.bias
INFO:__main__: Enc. parameter: module.layer3.3.conv3.weight
INFO:__main__: Enc. parameter: module.layer3.3.bn3.weight
INFO:__main__: Enc. parameter: module.layer3.3.bn3.bias
INFO:__main__: Enc. parameter: module.layer3.4.conv1.weight
INFO:__main__: Enc. parameter: module.layer3.4.bn1.weight
INFO:__main__: Enc. parameter: module.layer3.4.bn1.bias
INFO:__main__: Enc. parameter: module.layer3.4.conv2.weight
INFO:__main__: Enc. parameter: module.layer3.4.bn2.weight
INFO:__main__: Enc. parameter: module.layer3.4.bn2.bias
INFO:__main__: Enc. parameter: module.layer3.4.conv3.weight
INFO:__main__: Enc. parameter: module.layer3.4.bn3.weight
INFO:__main__: Enc. parameter: module.layer3.4.bn3.bias
INFO:__main__: Enc. parameter: module.layer3.5.conv1.weight
INFO:__main__: Enc. parameter: module.layer3.5.bn1.weight
INFO:__main__: Enc. parameter: module.layer3.5.bn1.bias
INFO:__main__: Enc. parameter: module.layer3.5.conv2.weight
INFO:__main__: Enc. parameter: module.layer3.5.bn2.weight
INFO:__main__: Enc. parameter: module.layer3.5.bn2.bias
INFO:__main__: Enc. parameter: module.layer3.5.conv3.weight
INFO:__main__: Enc. parameter: module.layer3.5.bn3.weight
INFO:__main__: Enc. parameter: module.layer3.5.bn3.bias
INFO:__main__: Enc. parameter: module.layer4.0.conv1.weight
INFO:__main__: Enc. parameter: module.layer4.0.bn1.weight
INFO:__main__: Enc. parameter: module.layer4.0.bn1.bias
INFO:__main__: Enc. parameter: module.layer4.0.conv2.weight
INFO:__main__: Enc. parameter: module.layer4.0.bn2.weight
INFO:__main__: Enc. parameter: module.layer4.0.bn2.bias
INFO:__main__: Enc. parameter: module.layer4.0.conv3.weight
INFO:__main__: Enc. parameter: module.layer4.0.bn3.weight
INFO:__main__: Enc. parameter: module.layer4.0.bn3.bias
INFO:__main__: Enc. parameter: module.layer4.0.downsample.0.weight
INFO:__main__: Enc. parameter: module.layer4.0.downsample.1.weight
INFO:__main__: Enc. parameter: module.layer4.0.downsample.1.bias
INFO:__main__: Enc. parameter: module.layer4.1.conv1.weight
INFO:__main__: Enc. parameter: module.layer4.1.bn1.weight
INFO:__main__: Enc. parameter: module.layer4.1.bn1.bias
INFO:__main__: Enc. parameter: module.layer4.1.conv2.weight
INFO:__main__: Enc. parameter: module.layer4.1.bn2.weight
INFO:__main__: Enc. parameter: module.layer4.1.bn2.bias
INFO:__main__: Enc. parameter: module.layer4.1.conv3.weight
INFO:__main__: Enc. parameter: module.layer4.1.bn3.weight
INFO:__main__: Enc. parameter: module.layer4.1.bn3.bias
INFO:__main__: Enc. parameter: module.layer4.2.conv1.weight
INFO:__main__: Enc. parameter: module.layer4.2.bn1.weight
INFO:__main__: Enc. parameter: module.layer4.2.bn1.bias
INFO:__main__: Enc. parameter: module.layer4.2.conv2.weight
INFO:__main__: Enc. parameter: module.layer4.2.bn2.weight
INFO:__main__: Enc. parameter: module.layer4.2.bn2.bias
INFO:__main__: Enc. parameter: module.layer4.2.conv3.weight
INFO:__main__: Enc. parameter: module.layer4.2.bn3.weight
INFO:__main__: Enc. parameter: module.layer4.2.bn3.bias
INFO:__main__: Dec. parameter: module.p_ims1d2_outl1_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g1_pool.0.1_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g1_pool.0.2_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g1_pool.0.3_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g1_pool.0.4_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g1_b3_joint_varout_dimred.weight
INFO:__main__: Dec. parameter: module.p_ims1d2_outl2_dimred.weight
INFO:__main__: Dec. parameter: module.adapt_stage2_b2_joint_varout_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g2_pool.0.1_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g2_pool.0.2_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g2_pool.0.3_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g2_pool.0.4_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g2_b3_joint_varout_dimred.weight
INFO:__main__: Dec. parameter: module.p_ims1d2_outl3_dimred.weight
INFO:__main__: Dec. parameter: module.adapt_stage3_b2_joint_varout_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g3_pool.0.1_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g3_pool.0.2_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g3_pool.0.3_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g3_pool.0.4_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g3_b3_joint_varout_dimred.weight
INFO:__main__: Dec. parameter: module.p_ims1d2_outl4_dimred.weight
INFO:__main__: Dec. parameter: module.adapt_stage4_b2_joint_varout_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g4_pool.0.1_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g4_pool.0.2_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g4_pool.0.3_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.mflow_conv_g4_pool.0.4_outvar_dimred.weight
INFO:__main__: Dec. parameter: module.clf_conv.weight
INFO:__main__: Dec. parameter: module.clf_conv.bias
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu line=266 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "/home/robot/PycharmProjects/light-weight-refinenet_train/src/train.py", line 422, in <module>
    main()
  File "/home/robot/PycharmProjects/light-weight-refinenet_train/src/train.py", line 406, in main
    epoch_start, segm_crit,args.freeze_bn[task_idx])
  File "/home/robot/PycharmProjects/light-weight-refinenet_train/src/train.py", line 279, in train_segmenter
    optim_enc.step()
  File "/home/robot/fangyu_pytorch/lib/python3.6/site-packages/torch/optim/sgd.py", line 93, in step
    d_p.add_(weight_decay, p.data)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:266`

**Comment by DrSleep** [comment]
What kind of data do you use?

In my experience, this error is usually seen when your target masks have labels larger than the channel dimension of your prediction present. 
As a sanity check, you can print `soft_output.size(1)` and `torch.unique(target_var)` before computing the loss

**Comment by csufangyu** [comment]
> What kind of data do you use?
> 
> In my experience, this error is usually seen when your target masks have labels larger than the channel dimension of your prediction present.
> As a sanity check, you can print `soft_output.size(1)` and `torch.unique(target_var)` before computing the loss

 thanks very much! I use NYUv2,but I find 56 classes!
`40
56
tensor([  0,   2,   3,   5,   6,   7,   8,   9,  11,  13,  14,  15,  17,  19,
         20,  21,  24,  34,  35,  36,  39,  42,  45,  49,  55,  59,  64,  70,
         73,  74,  75,  80,  82,  83,  93, 111, 113, 119, 133, 138, 141, 144,
        148, 156, 157, 158, 160, 161, 175, 177, 181, 206, 234, 239, 243, 255],
       device='cuda:0')`

**Comment by DrSleep** [comment]
everything above 39 should not be there. check out the NYUDv2 instruction from their site - you may need to run a matlab script to convert the labels

I will try to upload the dataset with the correct labels this week

**Comment by csufangyu** [comment]
> everything above 39 should not be there. check out the NYUDv2 instruction from their site - you may need to run a matlab script to convert the labels
> 
> I will try to upload the dataset with the correct labels this week
I have solved it !thanks very much!

**Comment by DrSleep** [comment]
great, no worries!
